[package]
name = "fate-gx"
description = "GX is a wrapper around reasonably modern OpenGL."
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
bitflags = "1.0"
fate-math = { path = "../math" }
fate-gl = { path = "../gl", features = ["post-hook"] }
