[package]
name = "fate-test-game"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
fate = { path = "../fate" }
dmc = { path = "../../dmc" }
sdl2 = "~0.31.0"
log = "~0.4.2"
pretty_env_logger = "~0.2.4"
backtrace = "~0.3.5"
gltf = "~0.11.2"
