[package]
name = "fate-font"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]
build = "build.rs"

[dependencies]
fate-img = { path = "../img" }
fate-math = { path = "../math" }
freetype-sys = "~0.7.0"
libc = "~0.2.42" # For c_void used by callbacks in FreeType. Urgh.

[build-dependencies]
hyper = "0.12.6"