[package]
name = "fate-font"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
vek = { version = "~0.9" }
#freetype-sys = "~0.6"
freetype-sys = { path = "../../freetype-sys" }
imgref = "~1.3.4"
libc = "~0.2.42" # For c_void used by callbacks in FreeType. Urgh.
